#!/usr/bin/env bash
#
# go-live.sh — fill in the variables below, then run:  bash go-live.sh
#
# What it does, in order:
#   1. Writes .env.local from the values you set below
#   2. Ensures GitHub CLI (gh) is authenticated  (interactive if needed)
#   3. Ensures Cloudflare Wrangler is authenticated  (interactive if needed)
#   4. Creates the GitHub repo (or pushes to it if it already exists)
#   5. Installs deps + builds the site
#   6. Creates the Cloudflare Pages project (idempotent) + deploys ./dist
#   7. Prints the live URL and any follow-up steps
#
# What it does NOT do (browser-only or one-time dashboard steps):
#   - Connect the GitHub repo to Cloudflare Pages for auto-deploy on push
#     (do this once in Pages dashboard → Connect Git → existing repo)
#   - Custom domain setup (Pages → custom domains)
#   - Tina Cloud project creation (sign up at app.tina.io and copy creds in)
#
# Re-running is safe. Idempotent on every step.

set -euo pipefail

# =============================================================================
#  FILL THESE IN
# =============================================================================

# Your GitHub username (e.g. "ncason"). Required to create the repo.
GITHUB_USER=""

# Repo visibility: "public" or "private"
REPO_VISIBILITY="public"

# Formspree action URL from https://formspree.io (after creating a form).
# Leave empty to ship without the contact form (page falls back to mailto).
FORMSPREE_ENDPOINT=""

# Tina Cloud creds from https://app.tina.io (after creating a project that
# points at your GitHub repo). Leave both empty to skip Tina for now —
# the site still ships; the /admin/ CMS just isn't wired yet.
TINA_PUBLIC_CLIENT_ID=""
TINA_TOKEN=""

# Cloudflare Pages project name (lowercase, unique in your CF account).
CF_PROJECT_NAME="studio-marginalia"

# Optional contact-fallback email (shown on the work page when Formspree is
# empty). Defaults to a placeholder if you leave this blank.
CONTACT_EMAIL="hello@studiomarginalia.com"

# =============================================================================
#  Don't edit below unless you know what you're doing.
# =============================================================================

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_DIR"

red()   { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
dim()   { printf '\033[2m%s\033[0m\n' "$*"; }
note()  { echo; printf '\033[1;35m▶ %s\033[0m\n' "$*"; }
ok()    { printf '  \033[32m✓\033[0m %s\n' "$*"; }
err()   { red "ERROR: $*" >&2; exit 1; }

[[ -d .git ]]                              || err "not in a git repo (run this from the studio-marginalia/ root)"
[[ -n "$GITHUB_USER" ]]                    || err "fill in GITHUB_USER at the top of this script"
[[ "$REPO_VISIBILITY" =~ ^(public|private)$ ]] || err "REPO_VISIBILITY must be public or private"
command -v node >/dev/null                 || err "node not found"
command -v pnpm >/dev/null                 || err "pnpm not found (install with: npm i -g pnpm@9)"
command -v gh >/dev/null                   || err "gh not found (install with: brew install gh)"

# -----------------------------------------------------------------------------
note "1/6 · writing .env.local"
cat > .env.local <<EOF_ENV
# generated by go-live.sh — edit by hand or re-run the script
TINA_PUBLIC_CLIENT_ID=${TINA_PUBLIC_CLIENT_ID}
TINA_TOKEN=${TINA_TOKEN}
NEXT_PUBLIC_TINA_BRANCH=main
PUBLIC_FORMSPREE_ENDPOINT=${FORMSPREE_ENDPOINT}
PUBLIC_CONTACT_EMAIL=${CONTACT_EMAIL}
TTS_ENDPOINT=http://precision-node4:8000
TTS_MODEL=speaches-ai/Kokoro-82M-v1.0-ONNX
TTS_VOICE=af_bella
PUBLIC_SITE_URL=https://${CF_PROJECT_NAME}.pages.dev
EOF_ENV
ok "wrote .env.local"

# -----------------------------------------------------------------------------
note "2/6 · GitHub auth"
if ! gh auth status >/dev/null 2>&1; then
  dim "  not logged in — opening GitHub auth flow (will prompt in this terminal)"
  gh auth login
fi
GH_LOGIN="$(gh api user -q .login 2>/dev/null || echo unknown)"
ok "gh authenticated as ${GH_LOGIN}"
if [[ "$GH_LOGIN" != "$GITHUB_USER" && "$GH_LOGIN" != "unknown" ]]; then
  dim "  note: gh is signed in as '${GH_LOGIN}' but GITHUB_USER is '${GITHUB_USER}'"
  dim "  (this is fine if you have permission to create repos under both)"
fi

# -----------------------------------------------------------------------------
note "3/6 · Cloudflare Wrangler auth"
if ! npx --yes wrangler whoami >/dev/null 2>&1; then
  dim "  not logged in — opening Cloudflare auth flow (browser)"
  npx --yes wrangler login
fi
ok "wrangler authenticated ($(npx --yes wrangler whoami 2>/dev/null | grep -E 'You are logged in|email' | head -1 | sed 's/.*as //;s/ with.*$//'))"

# -----------------------------------------------------------------------------
note "4/6 · GitHub repo: ${GITHUB_USER}/${CF_PROJECT_NAME}"
if gh repo view "${GITHUB_USER}/${CF_PROJECT_NAME}" >/dev/null 2>&1; then
  ok "repo exists"
  if ! git remote get-url origin >/dev/null 2>&1; then
    git remote add origin "https://github.com/${GITHUB_USER}/${CF_PROJECT_NAME}.git"
  fi
  if [[ -n "$(git status --porcelain)" ]]; then
    dim "  staging dirty working tree"
    git add -A
    git -c user.email="${GH_LOGIN}@users.noreply.github.com" \
        -c user.name="${GH_LOGIN}" \
        commit -m "chore: pre-deploy snapshot" || true
  fi
  git push -u origin main
else
  dim "  creating new ${REPO_VISIBILITY} repo + pushing"
  gh repo create "${GITHUB_USER}/${CF_PROJECT_NAME}" \
    "--${REPO_VISIBILITY}" \
    --source=. \
    --remote=origin \
    --push \
    --description "Studio Marginalia — personal site for Nina Pfeiffer"
fi
ok "github sync complete: https://github.com/${GITHUB_USER}/${CF_PROJECT_NAME}"

# -----------------------------------------------------------------------------
note "5/6 · Install + build"
pnpm install
pnpm build
ok "built dist/ ($(du -sh dist 2>/dev/null | awk '{print $1}'))"

# -----------------------------------------------------------------------------
note "6/6 · Cloudflare Pages deploy: ${CF_PROJECT_NAME}"
# Idempotent project create; ignore failure if it already exists.
npx --yes wrangler pages project create "${CF_PROJECT_NAME}" \
  --production-branch main \
  --compatibility-date "$(date -u +%Y-%m-%d)" \
  >/dev/null 2>&1 || dim "  project already exists or auto-creates on deploy — continuing"

npx --yes wrangler pages deploy ./dist \
  --project-name="${CF_PROJECT_NAME}" \
  --branch=main \
  --commit-dirty=true

LIVE_URL="https://${CF_PROJECT_NAME}.pages.dev"
echo
green "Done."
echo
echo "  Live:        ${LIVE_URL}"
echo "  GitHub:      https://github.com/${GITHUB_USER}/${CF_PROJECT_NAME}"
echo
echo "  Optional one-time dashboard steps:"
echo "    • Auto-deploy on push:  CF dashboard → Workers & Pages → ${CF_PROJECT_NAME}"
echo "      → Settings → Builds & deployments → Connect to Git → ${GITHUB_USER}/${CF_PROJECT_NAME}"
echo "      Build command: pnpm build  ·  Output dir: dist"
echo "    • Add env vars in Pages → Settings → Environment variables (paste from .env.local)"
echo "    • Custom domain: Pages → ${CF_PROJECT_NAME} → Custom domains → Set up"
echo
if [[ -z "$TINA_PUBLIC_CLIENT_ID" ]]; then
  echo "  Tina CMS skipped (TINA_* not filled). Sign up at app.tina.io and re-run."
fi
if [[ -z "$FORMSPREE_ENDPOINT" ]]; then
  echo "  Formspree skipped. Contact form falls back to mailto:${CONTACT_EMAIL}"
fi
echo
